### ISSUE TITLE
Create a "virtual gearbox"

### ISSUE THREAD

**Issue by zeroClearAmerican** [zeroClearAmerican/PrimeMovers_TestBench#21]
Create a virtual gearbox which can swap the speed of the drivetrain between two preset values. Accomplish this by multiplying the speed by a coefficient to achieve the desired speed output.

There are several places where the speed can be changed:
- Joystick inputs
- Chassis speeds
- Motor output(s)
- Chassis max speed

Which one works best? Which one achieves the desired hi/lo-gear behavior without sacrificing control?

**Comment by DjAce626** [comment]
I created a button that changes the speed. this satisfy the requirements
