### ISSUE TITLE
Controller inputs too sensitive

### ISSUE THREAD

**Issue by Supazz** [zeroClearAmerican/PrimeMovers_TestBench#4]
When controlling the robot gently it the ramp from 0 to max power is very short and difficult to control.

**Comment by zeroClearAmerican** [comment]
DEMO comment: Have you tried applying a square root to the controller inputs to smooth the curve?

**Comment by zeroClearAmerican** [comment]
@richard-mungai  and @Supazz discussed this with a robot driver and determined that this is not needed at this time.
