### ISSUE TITLE
Swerve drive odometry not fed

### ISSUE THREAD

**Issue by zeroClearAmerican** [zeroClearAmerican/PrimeMovers_TestBench#5]
The swerve drive subsystem does not implement an odometer for tracking the state of the system. 
Use the guide at https://docs.wpilib.org/en/stable/docs/software/kinematics-and-odometry/swerve-drive-odometry.html to implement the odometer.

**Comment by richard-mungai** [comment]
I was able to make the SwerveDriveOdometry but having problems with the swerve module position.

**Comment by zeroClearAmerican** [comment]
For context, @richard-mungai and I looked at the examples and couldn't find a way to get the total distance traveled from the encoder, since the built-in encoder from the drive Falcon motor is what's used for drive tracking. 

I searched chief delphi and found [this thread](https://www.chiefdelphi.com/t/swerve-module-position/424449/2) where another team encountered the same issue. Essentially, we must convert from the falcon's encoder output (raw sensor units) into meters traveled using the sensor position, the wheel circumference, and the drive gear ratio. 

I pushed a couple of new commits to the branch that should now feed the odometry properly from the `PrimeSwerveModuleSubsystem.getPosition()` function below. 

```
 public SwerveModulePosition getPosition() {
  return new SwerveModulePosition(
    CTREConverter.falconToMeters(
      mDriveMotor.getSelectedSensorPosition(), 
      RobotMap.kDriveWheelCircumference, 
      RobotMap.kDriveGearRatio
    ), 
    mEncoder.getRotation2d());
 }
```

Please test this change by using the output `Pose2d` from the `m_Odometry.update()` function to feed a Field2d object, which should be created in the `SwerveDriveTrainSubsystem`. [Here](https://docs.wpilib.org/en/stable/docs/software/dashboards/glass/field2d-widget.html) is the information document which defines how to use the Field2d and how to visualize the data for debugging purposes.
