### ISSUE TITLE
Adjust naming scheme to standard Java nomenclature

### ISSUE THREAD

**Issue by zeroClearAmerican** [zeroClearAmerican/PrimeMovers_TestBench#9]
In Java programs, names with underscores are not compliant with CamelCase style guidelines, which can be found [here](https://www.techtarget.com/whatis/definition/CamelCase). 

For all variables in the program that contain "_", please remove it and make sure the variable name conforms to standard camel-case style.

**Comment by richard-mungai** [comment]
I was able to finish the CamelCase naming scheme.
